language: objective-c
osx_image: xcode7
before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap --platform iOS
script: xcodebuild -project Habits.xcodeproj -scheme Habits -configuration Debug -sdk iphonesimulator -destination 'name=iPhone 6s Plus' test
